from tkinter import *
from PIL import Image, ImageTk

dict1={ }
img=Image.open("animal_pictures/elefant.png")
dict1["e"]=img
img=Image.open("animal_pictures/cat.jpg")
dict1["c"]=img
img=Image.open("animal_pictures/lion.png")
dict1["l"]=img
img=Image.open("animal_pictures/dog.png")
dict1["d"]=img
img=Image.open("animal_pictures/monkey.jpg")
dict1["m"]=img
img=Image.open("animal_pictures/bat.png")
dict1["b"]=img
img=Image.open("animal_pictures/giraffe.png")
dict1["g"]=img
img=Image.open("animal_pictures/alpaca.png")
dict1["a"]=img
img=Image.open("animal_pictures/fish.png")
dict1["f"]=img
img=Image.open("animal_pictures/horse.png")
dict1["h"]=img
img=Image.open("animal_pictures/iguana.png")
dict1["i"]=img
img=Image.open("animal_pictures/kangaroo.png")
dict1["k"]=img
img=Image.open("animal_pictures/owl.png")
dict1["o"]=img
img=Image.open("animal_pictures/narwhal.png")
dict1["n"]=img
img=Image.open("animal_pictures/penguin.png")
dict1["p"]=img
img=Image.open("animal_pictures/quoll.png")
dict1["q"]=img
img=Image.open("animal_pictures/rabbit.png")
dict1["r"]=img
img=Image.open("animal_pictures/shark.png")
dict1["s"]=img
img=Image.open("animal_pictures/tiger.png")
dict1["t"]=img
img=Image.open("animal_pictures/unicorn.png")
dict1["u"]=img
img=Image.open("animal_pictures/viper.png")
dict1["v"]=img
img=Image.open("animal_pictures/unicorn.png")
dict1["u"]=img
img=Image.open("animal_pictures/wolf.png")
dict1["w"]=img
img=Image.open("animal_pictures/xerus.png")
dict1["x"]=img
img=Image.open("animal_pictures/yak.png")
dict1["y"]=img
dict1["j"]="animal_pictures/jellyfish.png"

