IMAGE_SIZE = 150

LETTERS_IMAGES_DICT = {'A' : 'Letters_images/A.jpg', 'B' : 'Letters_images/B.jpg',
                       'C' : 'Letters_images/C.jpg', 'D' : 'Letters_images/D.jpg',
                       'E' : 'Letters_images/E.jpg', 'F' : 'Letters_images/F.jpg',
                       'G' : 'Letters_images/G.jpg', 'H' : 'Letters_images/H.jpg',
                       'I' : 'Letters_images/I.jpg', 'J' : 'Letters_images/J.jpg',
                       'K' : 'Letters_images/K.jpg', 'L' : 'Letters_images/L.jpg',
                       'M' : 'Letters_images/M.jpg', 'N' : 'Letters_images/N.jpg',
                       'O' : 'Letters_images/O.jpg', 'P' : 'Letters_images/P.jpg',
                       'Q' : 'Letters_images/Q.jpg', 'R' : 'Letters_images/R.jpg',
                       'S' : 'Letters_images/S.jpg', 'T' : 'Letters_images/T.jpg',
                       'U' : 'Letters_images/U.jpg', 'V' : 'Letters_images/V.jpg',
                       'W' : 'Letters_images/W.jpg', 'X' : 'Letters_images/X.jpg',
                       'Y' : 'Letters_images/Y.jpg', 'Z' : 'Letters_images/Z.jpg',
                       'a' : 'Letters_images/a2.jpg', 'b' : 'Letters_images/b2.jpg',
                       'c' : 'Letters_images/c2.jpg', 'd' : 'Letters_images/d2.jpg',
                       'e' : 'Letters_images/e2.jpg', 'f' : 'Letters_images/f2.jpg',
                       'g' : 'Letters_images/g2.jpg', 'h' : 'Letters_images/h2.jpg',
                       'i' : 'Letters_images/i2.jpg', 'j' : 'Letters_images/j2.jpg',
                       'k' : 'Letters_images/k2.jpg', 'l' : 'Letters_images/l2.jpg',
                       'm' : 'Letters_images/m2.jpg', 'n' : 'Letters_images/n2.jpg',
                       'o' : 'Letters_images/o2.jpg', 'p' : 'Letters_images/p2.jpg',
                       'q' : 'Letters_images/q2.jpg', 'r' : 'Letters_images/r2.jpg',
                       's' : 'Letters_images/s2.jpg', 't' : 'Letters_images/t2.jpg',
                       'u' : 'Letters_images/u2.jpg', 'v' : 'Letters_images/v2.jpg',
                       'w' : 'Letters_images/w2.jpg', 'x' : 'Letters_images/x2.jpg',
                       'y' : 'Letters_images/y2.jpg', 'z' : 'Letters_images/z2.jpg'}